### ISSUE TITLE
Codecademy's project requirements

### ISSUE THREAD

**Issue by bstojkovic** [bstojkovic/Codecademy-CS-Project-2-Blackjack#1]
### Basic Requirements

- [x] User Story: As a user I want to clearly see the cards dealt to me and to the dealer. 2ad8c7e03e8fe215007750c968b475b12477a436
- [x] User Story: As a user I want to be able to choose to stay. 10ad632e93eebac879865ba83fc118d9cd7c1c53
- [x] User Story: As a user I want to be able to choose to hit until I choose to stay or until I bust. 7ab1d142d7a5d1e13e1c876a14c5ce314aea5eac
- [x] User Story: As a user I want to clearly see the sequence of moves made by the dealer. ff07deac5b8574ffd46903907d58069a948a4c5c
- [x] User Story: As a user I want to clearly see who won and why. b416ce8357045bb2ba8145ebcf01fc3382f63df3
- [x] User Story: As a user I want to be able to quit the game or go again after each cycle. 1cff4b3dc95d092c13b245b4adff2b1b371953a2

### Intermediate Challenge

- [x] User Story: As a user I want the game to incorporate a virtual chip/currency system to simulate real-life staking mechanics.
  - [x] Implement Player and Dealer classes (#2) to hold chips 797d7a0543e2a5e8934e162b9842b77be024bb12
  - [x] Implement chip stacks (#3) 692b1dfe079c5537be4c0d1604977d59aa588a81
- [x] User Story: As a user I want to clearly see my chip stack, as well as that of the dealer. 1d29e71f577c4133325f71c23c9a438c90984197
- [x] User Story: As a user I want to be able to vary my bet according to the min/max betting rules.
  - [x] Add betting 912eb084d66ff4e54ab7fd00562a5e3791fb179b
  - [x] Add blackjack win condition (#6) d426d064984ceb6281a3dcc9d90c2675526e584d
  - [x] Add bet collection (#5) 71acabcc430a6f4e030f603202ea676ac15026c2

### Advanced Challenge

- [x] User Story: As a user I want to be able to choose to split my hand whenever possible. 5bec92ec9d9234e61aeb72bdac53b15dcaf2c98c
- [x] User Story: As a user I want to be able to choose to double down whenever possible. cf8cccca1e4025381767b7fba43a0a737cb44eb6
